# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(417, 223)
        self.comboBox_0 = QtWidgets.QComboBox(Widget)
        self.comboBox_0.setGeometry(QtCore.QRect(90, 20, 69, 22))
        self.comboBox_0.setObjectName("comboBox_0")
        self.comboBox_1 = QtWidgets.QComboBox(Widget)
        self.comboBox_1.setGeometry(QtCore.QRect(90, 60, 69, 22))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_2 = QtWidgets.QComboBox(Widget)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 100, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.uhdlabel_0 = QtWidgets.QLabel(Widget)
        self.uhdlabel_0.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.uhdlabel_0.setObjectName("uhdlabel_0")
        self.uhdlabel_1 = QtWidgets.QLabel(Widget)
        self.uhdlabel_1.setGeometry(QtCore.QRect(30, 60, 71, 21))
        self.uhdlabel_1.setObjectName("uhdlabel_1")
        self.uhdlabel_2 = QtWidgets.QLabel(Widget)
        self.uhdlabel_2.setGeometry(QtCore.QRect(30, 100, 71, 21))
        self.uhdlabel_2.setObjectName("uhdlabel_2")
        self.startButton_0 = QtWidgets.QPushButton(Widget)
        self.startButton_0.setGeometry(QtCore.QRect(190, 20, 75, 31))
        self.startButton_0.setObjectName("startButton_0")
        self.startButton_1 = QtWidgets.QPushButton(Widget)
        self.startButton_1.setGeometry(QtCore.QRect(190, 60, 75, 31))
        self.startButton_1.setObjectName("startButton_1")
        self.startButton_2 = QtWidgets.QPushButton(Widget)
        self.startButton_2.setGeometry(QtCore.QRect(190, 100, 75, 31))
        self.startButton_2.setObjectName("startButton_2")
        self.endButton_0 = QtWidgets.QPushButton(Widget)
        self.endButton_0.setGeometry(QtCore.QRect(290, 22, 51, 31))
        self.endButton_0.setObjectName("endButton_0")
        self.endButton_1 = QtWidgets.QPushButton(Widget)
        self.endButton_1.setGeometry(QtCore.QRect(290, 60, 51, 31))
        self.endButton_1.setObjectName("endButton_1")
        self.endButton_2 = QtWidgets.QPushButton(Widget)
        self.endButton_2.setGeometry(QtCore.QRect(290, 100, 51, 31))
        self.endButton_2.setObjectName("endButton_2")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(20, 180, 381, 41))
        self.label.setObjectName("label")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "肥鹅WOW玛拉顿挖矿辅助"))
        self.uhdlabel_0.setText(_translate("Widget", "采集卡0"))
        self.uhdlabel_1.setText(_translate("Widget", "采集卡1"))
        self.uhdlabel_2.setText(_translate("Widget", "采集卡2"))
        self.startButton_0.setText(_translate("Widget", "开始运行"))
        self.startButton_1.setText(_translate("Widget", "开始运行"))
        self.startButton_2.setText(_translate("Widget", "开始运行"))
        self.endButton_0.setText(_translate("Widget", "结束"))
        self.endButton_1.setText(_translate("Widget", "结束"))
        self.endButton_2.setText(_translate("Widget", "结束"))
        self.label.setText(_translate("Widget", "本脚本由肥鹅编写制作，仅供内部研究学习，如恶意传播牟利造成的法\n"
"律问题，与本人无关。联系方式：80491636"))
